### PR TITLE
Adding pt (Portuguese) + fix add check whether textbox is empty befor…

### PR DESCRIPTION
**Pull request by brunojuliao**
…e alert. It was triggering the alert after uncheck (even when it was empty).

### CODE REVIEW

**Comment by checkdigits** [comment]
Hi @brunojuliao - did you mean to add this pull request to Jeff's origin/dev - or - master?

Your PR is against my fork, isn't it, when it should be against Jeff's original - or have I misunderstood something (which is quite likely)?

The master is found here: https://github.com/csharpfritz/Fritz.EpicBuildMusic

**Comment by brunojuliao** [comment]
Just to have documented here, I was working on add internationalization. Then I realized that you sent a pull request with improvements, so I deleted the fork I had based on Jeff's and created a new one based on yours. After that, I did my changes and a small fix.
I still could not "internationalize" the menu items (the values on "ProvideOptionPage" in BuildMusicPackage.cs, but I did change one alert content, the file dialog's title and the label's content.

**Comment by checkdigits** [comment]
After offline email clarified -

@checkdigits will review and resubmit @brunojuliao changes for addition of Portuguese strings and null check line to @csharpfritz

**Comment by checkdigits** [comment]
Nice work @brunojuliao - merged into dev and my pull request on Jeff's origin/dev

**Pull request merged**
